# Generated by Django 3.1.5 on 2021-01-26 14:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('times', '0002_auto_20210126_1425'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reserved',
            new_name='Reservation',
        ),
    ]
