# Generated by Django 3.1.5 on 2021-01-27 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0004_freetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='times.service'),
        ),
    ]
