# Generated by Django 3.1.5 on 2021-01-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0005_auto_20210127_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='break_time',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
