# Generated by Django 3.1.5 on 2021-02-17 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0006_service_break_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='duration',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
    ]
